[package]
name = "chatgpt"
version = "0.4.1"
edition = "2021"
description = "ChatGPT API Wrapper"
authors = ["Maxuss <maxus.info.mail@proton.me>"]
license = "MIT or Apache 2.0"
repository = "https://github.com/Maxuss/chatgpt_rs"
keywords = ["ChatGPT", "OpenAI"]
categories = ["api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json", "stream"] }
tokio = { version = "1.23.0", features = ["macros"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
thiserror = "1.0.37"
futures-util = "0.3.25"
bytes = "1.3.0"

[dev-dependencies]
futures = "0.3.25"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
