[package]
name = "chatgpt_rs"
version = "1.0.0"
edition = "2021"
description = "ChatGPT API Wrapper"
authors = ["Maxuss <maxus.info.mail@proton.me>"]
license = "MIT"
repository = "https://github.com/Maxuss/chatgpt_rs"
keywords = ["ChatGPT", "OpenAI"]
categories = ["api-bindings"]

[lib]
name = "chatgpt"
path = "./src/chatgpt.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json"] }
tokio = { version = "1.26.0", features = ["macros"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.93", optional = true }
thiserror = "1.0.38"
url = "2.3.1"
chrono = "0.4.23"
derive_builder = "0.12.0"

postcard = { version = "1.0.4", features = ["alloc"], optional = true }
eventsource-stream = { version = "0.2.3", optional = true }
futures = { version = "0.3.26", optional = true }
futures-util = { version = "0.3.26", optional = true }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }

[features]
default = ["json"]
streams = [
    "dep:eventsource-stream",
    "dep:futures-util",
    "dep:futures",
    "reqwest/stream",
]
json = ["dep:serde_json", "tokio/fs"]
postcard = ["dep:postcard", "tokio/fs"]
