[package]
name = "chatgpt_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json", "cookies"] }
tokio = { version = "1.23.0", features = ["macros"] }
serde = { version = "1.0.149", features = ["derive"] }
thiserror = "1.0.37"
