[package]
name = "chatgpt_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.13", features = ["json", "cookies", "stream"] }
tokio = { version = "1.23.0", features = ["macros"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
thiserror = "1.0.37"
futures-util = "0.3.25"
